name: "Terraform-Comment"
description: "terraform result as PR comment"
branding:
  icon: "lock"
  color: "green"
inputs:
  type:
    description: "Comment type"
    default: "plan"
    required: true
  inputFile:
    description: "Comment input"
    default: "plan"
    required: true
  include:
    description: "Comment sections included"
    default: "outside,action,output"
    required: true
  exclude:
    description: "Comment sections excluded"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
