name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Typical Usage
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v6
        id: read-plan
        with:
          script: |
            const fs = require("fs")
            return fs.readFileSync("./.github/plan3.stdout")
      - name: Terraform comment PR
        uses: "./"
        with:
          type: plan
          input: ${{ steps.read-plan.outputs.result }}
          sections: "actions"
