name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Typical Usage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform comment PR
        uses: "./"
        with:
          comment_type: plan
          comment_input: aaaaa!!!
