name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Typical Usage
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform comment PR
        uses: "./"
        with:
          type: plan
          inputFile: ./.github/plan3.stdout
          sections: "actions"
